# Generated by Django 6.1.1 on 2026-10-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, max_length=30)),
                ('hometown', models.CharField(max_length=100)),
                ('year_level', models.PositiveSmallIntegerField()),
                ('favorite_subject', models.CharField(max_length=100)),
                ('club', models.CharField(blank=True, max_length=100)),
                ('motto', models.CharField(blank=True, max_length=150)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
